### ISSUE TITLE
Frontal Armour miscalculation/confusion

### ISSUE THREAD

**Issue by AlBaarS** [albinoonline/sprocketBlueprintValidator#1]
Hi albino creeper,

I am experiencing an issue with the calculation of the frontal armour of my vehicle. The plates on the front are either 55 or 25 mm thick, with the exception of the very heavily sloped nose armour (15mm), yet the Data Dump says that the frontal armour is only 16.91mm thick.

I have tried sussing out which plate(s) is causing the issue by increasing them all to 55mm, but while the weight increases, and the ingame armour thickness does too, the tool still says it's 16.91mm. There is no smoothing active, so I have no clue what is causing it.

I have attached the blueprint, screenshots, and the Data Dump below. If there is anything else you need, let me know.

Blueprint & screenshots: https://www.dropbox.com/s/6swfh0emdldn8as/EMI-2012%20Constantine%20WIP.zip?dl=0

Data Dump:

Name= EMI-2012 Constantine
Weight= 7.98T
Length= 4.76m
width= 1.74m raw hull or 2.2m simplified track
Height= 1.66m
400 liters of fuel, 400 of which is internal.
Engine= 7.6L V2
Transmission= 8 Speed transmission (5+3)
cannons:
 57X588mm BL1900: 1
Gun depression= -13.54
ammo:
 57X588mm: 50 rounds
crew:
 all: 5m^3
 commander: 1m^3
 driver: 1m^3
 gunner: 1m^3
 loader: 1m^3
 radioman: 1m^3
Hull Armor:
 Lowest:15mm
 Front:16.91mm
 Rear:15.52mm
 Side:15mm/15mm
 Top:15mm
 Bottom:15mm
Turret Armor:
 Lowest:15mm
 Front:53.89mm
 Rear:15mm
 Side:15.42mm/15.415493711276582mm
 Top:15.02mm
 Bottom:15mm
parts:
 viewport: 10
 hatch: 2
 rivetVariant: 86
 engineVent: 2
 decal: 5
 asset: 5
 mantlet: 1
 MTL: 1
 gunnerSight: 1
 cupola: 1
 spareWheel: 1
 AttachedPart: 1
 antenna: 1

**Comment by albinoonline** [comment]
It's usually some tiny plate that's hiding somewhere, I'll look at it when I get home it'll be about 4 hours though

**Comment by AlBaarS** [comment]
Thank you in advance. Luckily the TEABAG deadline is still a bit away :)

**Comment by albinoonline** [comment]
you have plates underneath your drivers compartment, if you clip through the front you can select and delete them
![20221229142215_1](https://user-images.githubusercontent.com/46507585/210016632-ffd36489-b762-417b-9851-4d563400f440.jpg)

**Comment by albinoonline** [comment]
sprocket seams real angry about those plates and deleting them. Here is a fixed BP, reading 47mm of armor, the lower plates need to be thicker that alone can get you up to 55mm of frontal armor, 
[fixed tank.zip](https://github.com/albinoonline/sprocketBlueprintValidator/files/10322369/fixed.tank.zip)

**Comment by AlBaarS** [comment]
Oh man, those sneaky plates! I was so sure I got them all. Thank you very much and sorry for bothering you with it
